import streamlit as st
from voice_advisor import (
    run_asr, generate_response, text_to_speech,
    LANG_NAMES, LANG_CODE
)

st.set_page_config(page_title="ArthaSetu Voice", page_icon="\U0001f3e6", layout="wide")
st.title("\U0001f3e6 ArthaSetu — Voice Financial Advisor")
st.caption("Speak in any Indian language. Get loan scheme advice with audio response.")

with st.sidebar:
    st.header("\U0001f464 User Profile")
    user_state = st.selectbox("State", [
        "Uttar Pradesh","Bihar","Maharashtra","Tamil Nadu",
        "Karnataka","West Bengal","Gujarat","Rajasthan",
        "Madhya Pradesh","Odisha","Andhra Pradesh","Telangana"
    ])
    xscore = st.slider("XScore", 300, 900, 510, help="Credit readiness score from XScore model")
    st.divider()
    st.subheader("\U0001f310 Supported Languages")
    st.write("Hindi, Tamil, Telugu, Marathi, Bengali, Gujarati, Kannada, Malayalam, English")
    st.divider()
    st.subheader("\U0001f4ca Pipeline")
    st.write("1. ASR: Sarvam Saaras v3")
    st.write("2. LLM: Sarvam-m 24B")
    st.write("3. TTS: Sarvam Bulbul v2")
    st.write("4. Data: 11 govt loan schemes")

col1, col2 = st.columns(2, gap="large")

with col1:
    st.subheader("\U0001f399\ufe0f Speak Your Query")
    st.caption("Ask in any Indian language")
    audio_input = st.audio_input("Record your question")
    st.markdown("---")
    st.subheader("\u2328\ufe0f Or Type Your Query")
    text_query = st.text_input("Type here", placeholder="e.g. mujhe sabzi ke liye loan chahiye")
    text_lang = st.selectbox("Response language", list(LANG_NAMES.keys()), format_func=lambda x: LANG_NAMES[x])

    if st.button("\U0001f50d Get My Recommendation", type="primary", use_container_width=True):
        if audio_input:
            with st.spinner("\U0001f3a7 Listening and transcribing..."):
                raw_text, english_text, lang = run_asr(audio_input.read())
                st.session_state["asr_done"] = True
        elif text_query:
            raw_text = text_query
            english_text = text_query
            lang = text_lang
            st.session_state["asr_done"] = True
        else:
            st.warning("Please record audio or type a question first")
            st.stop()

        with st.spinner("\U0001f4a1 Finding best schemes with Sarvam-m..."):
            reply = generate_response(english_text, lang, xscore, user_state)

        with st.spinner("\U0001f50a Generating voice response..."):
            audio_bytes = text_to_speech(reply, lang)

        st.session_state["result"] = {
            "lang": lang,
            "raw": raw_text,
            "english": english_text,
            "reply": reply,
            "audio": audio_bytes,
        }

with col2:
    st.subheader("\U0001f4ac Your Recommendation")
    if "result" in st.session_state:
        r = st.session_state["result"]
        st.info(f"**Language detected:** {LANG_NAMES.get(r['lang'], r['lang'])}")
        if r["raw"]:
            st.write("**You said:**", r["raw"])
        if r.get("english") and r["english"] != r["raw"]:
            st.write("**English:**", r["english"])
        st.success(r["reply"])
        if r["audio"]:
            st.audio(r["audio"], format="audio/wav")
            st.caption("\U0001f50a Audio generated by Sarvam Bulbul v2")
    else:
        st.info("Record your voice or type a question, then click Get My Recommendation")

st.divider()
st.caption("ArthaSetu \u2014 Powered by Sarvam AI + Databricks | Bharat Bricks Hacks 2026")
